GET http://localhost:8080/users
Content-Type: application/json

{}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

GET http://localhost:8080/users/62fb871b47b92578c8d30cec
Content-Type: application/json

{}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "lol",
  "password": "123124",
  "email": "lol@lol.com"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

PUT http://localhost:8080/users/62fb96501a012dd88f7bb7a2
Content-Type: application/json

{
  "id": "62fb96501a012dd88f7bb7a2",
  "username": "cringe",
  "password": "1231254",
  "email": "lol@lol.com"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###

DELETE http://localhost:8080/users/62fcbdf79ab50fcf2168e15a
Content-Type: application/json

{}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###